name: Generate Diagram

on:
  push:
    branches:
      - main

jobs:
  generate-diagram:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate repository diagram
        uses: githubocto/repo-visualizer@v1
        with:
          output: diagram.svg

      - name: Upload diagram artifact
        uses: actions/upload-artifact@v3
        with:
          name: diagram
          path: diagram.svg
