name: Generate Diagram

on:
  push:
    branches:
      - main

jobs:
  generate-diagram:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate repository diagram
        uses: githubocto/repo-visualizer@0.9.1
        with:
          output: diagram.svg

